spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mynewdb
    username: gribov
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: bookshop




